### ISSUE TITLE
The ttl method of MiniCache & Cache returns the expired timestamp

### ISSUE THREAD

**Issue by StevenJim13** [StKali/cache3#16]
```python
In [1]: from cache3 import MiniCache

In [2]: cache = MiniCache('sample')

In [3]: cache.set("key", "value", 10)
Out[3]: True

In [4]: cache.ttl("key")
Out[4]: 1684482355.1852028

In [5]: cache.ttl("key")  # 10s later
Out[5]: -1
```

**Comment by StKali** [comment]
Thank you for pointing out this issue. The expiration time is indeed taking effect because I forgot to subtract the current timestamp when calculating the TTL.

**Comment by StevenJim13** [comment]
I think I can help you fix it ~

**Comment by StKali** [comment]
> I think I can help you fix it ~

Thank you so much for your willingness to help me fix the bug in my project. I really appreciate it! Please let me know if you need any assistance or information from me to get started.
