### ISSUE TITLE
What unit is the TTL?

### ISSUE THREAD

**Issue by jeremylcarter** [StKali/cache3#3]
Hi, thanks for this library. I am finding it very useful. After reading the documentation I notice I cant see what units the TTL is in, is it seconds, milliseconds etc? I have assumed seconds since that seems to be the most common with other python libraries. Would you be able to confirm this?

Thank you!

**Comment by shreve** [comment]
Seconds, but it's a float so it should be able to support milliseconds.

https://github.com/StKali/cache3/blob/master/src/cache3/setting.py#L19

**Comment by jeremylcarter** [comment]
Thank you for your reply.

**Comment by StKali** [comment]
seconds, since it is a floating-point number, it also supports milliseconds, but that is not very precise

**Comment by StKali** [comment]
seconds, since it is a floating-point number, it also supports milliseconds, but that is not very precise
